on:
  workflow_call:
    inputs:
      package:
        required: true
        description: "Path to package"
        type: string

jobs:
  publish:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-suffix: "optional-suffix"

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - run: uv venv --python 3.12 .venv && source .venv/bin/activate && uv pip install -r pyproject.toml && uv pip install -U pip setuptools wheel build
        working-directory: ${{ inputs.package }}

      - run: python3 -m venv .venv/dev && source .venv/dev/bin/activate
        working-directory: ${{ inputs.package }}

      - run: source .venv/dev/bin/activate && pip install -U pip setuptools wheel 
        working-directory: ${{ inputs.package }}

      - name: Install build dependencies
        run: source .venv/dev/bin/activate && pip install -r dev-deps/python3.11/build.txt
        working-directory: ${{ inputs.package }}

      - name: Install dependencies
        run: source .venv/dev/bin/activate && pip install .
        working-directory: ${{ inputs.package }}

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - run: make build_all
        working-directory: ${{ inputs.package }}

      - name: Publish
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e
        with:
          verbose: true
          packages-dir: ${{ inputs.package }}/dist

permissions:
  contents: read
  id-token: write
