on:
  workflow_call:
    inputs:
      package:
        required: true
        description: "Path to package"
        type: string
      tag_prefix:
        required: true
        description: "Tag Prefix"
        type: string

jobs:
  version:
    runs-on: "ubuntu-latest"
    if: ${{ ! endsWith(github.event.head_commit.message, '[skip-version]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 'Automated Version Bump'
        id: version-bump
        uses: ambient-labs/bump-repo-version@main
        with:
          file_to_bump: "${{ inputs.package }}/pyproject.toml"
          bump_type: "patch"
          main_branch: "main"
          python_version: "3.12"
          tag_prefix: ${{ inputs.tag_prefix }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

permissions:
  contents: read
