on:
  workflow_call:
    inputs:
      package:
        required: true
        description: "Path to package"
        type: string

env:
  FORCE_COLOR: "1"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        # with:
        #   enable-cache: true
        #   cache-suffix: "optional-suffix"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          # python-version-file: ".python-version"
          # python-version-file: "pyproject.toml"
          python-version: 3.11

      - name: Lint
        run: make lint
        working-directory: ${{ inputs.package }}
