on:
  workflow_call:
    inputs:
      pyversion:
        required: true
        description: "Python version"
        type: string
      package:
        required: true
        description: "Path to package"
        type: string

env:
  FORCE_COLOR: "1"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        # with:
        #   enable-cache: true
        #   cache-suffix: "optional-suffix"

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.pyversion }}

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - run: uv venv --python ${{ inputs.pyversion }} .venv && source .venv/bin/activate && uv pip install -r pyproject.toml
        working-directory: ${{ inputs.package }}

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - run: make build_all
        working-directory: ${{ inputs.package }}

      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
