on:
  workflow_call:
    inputs:
      package:
        required: true
        description: "Path to package"
        type: string

env:
  FORCE_COLOR: "1"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          # python-version-file: ".python-version"
          # python-version-file: "pyproject.toml"
          python-version: 3.11
          cache: pip
          cache-dependency-path: ${{ inputs.package}}/dev-deps/python3.11/lint.txt

      - run: python3 -m venv .venv/dev && source .venv/dev/bin/activate
        working-directory: ${{ inputs.package }}

      - run: pip install -U pip setuptools wheel 
        working-directory: ${{ inputs.package }}

      - name: Install dependencies
        run: pip install -r dev-deps/python3.11/lint.txt
        working-directory: ${{ inputs.package }}

      - name: Lint
        run: make lint
        working-directory: ${{ inputs.package }}
