on:
  workflow_call:
    inputs:
      package:
        required: true
        description: "Path to package"
        type: string

env:
  FORCE_COLOR: "1"

jobs:
  unit-test:
    name: 'Unit Test ${{ matrix.pyversion }}'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # https://github.com/actions/python-versions/blob/main/versions-manifest.json
          # - pyversion: "3.12"
          - pyversion: "3.11"
            enable_coverage: true
          - pyversion: "3.12"
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ matrix.pyversion }}
      #     cache: pip
      #     cache-dependency-path: ${{ inputs.package }}/${{ format('python{0}', matrix.pyversion) }}/test.txt

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          # python-version-file: ".python-version"
          # python-version-file: "pyproject.toml"
          python-version: 3.11
          cache: pip
          cache-dependency-path: ${{ inputs.package}}/dev-deps/python3.11/lint.txt

      - run: python3 -m venv .venv/dev && source .venv/dev/bin/activate
        working-directory: ${{ inputs.package }}

      - run: python -m pip install -U pip setuptools wheel 
        working-directory: ${{ inputs.package }}

      - name: Install dev dependencies
        run: pip install -r dev-deps/${{ format('python{0}', matrix.pyversion) }}/test.txt
        working-directory: ${{ inputs.package }}

      - name: Install dependencies
        run: pip install .
        working-directory: ${{ inputs.package }}

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - run: make test
        working-directory: ${{ inputs.package }}

      - name: Upload coverage to Codecov  # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
        if: matrix.enable_coverage
        with:
          verbose: true
          files: ${{ inputs.package }}/coverage.xml
          fail_ci_if_error: false  # https://github.com/codecov/codecov-action/issues/557
