on:
  workflow_call:
    inputs:
      pyversion:
        required: true
        description: "Python version"
        type: string
      package:
        required: true
        description: "Path to package"
        type: string

env:
  FORCE_COLOR: "1"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-suffix: "optional-suffix"

      - name: Lint
        run: make lint
        working-directory: ${{ inputs.package }}
